Draft: rotate token with JWT token validation
jfrog/artifactory-secrets-plugin pull request #17
Opened 2022-06-13 16:29 UTC by TJM

**WIP** - This is my attempt to validate the JWT token. It does not work yet. This is a call for help.

Thanks,
Tommy

2022-11-17 13:20 UTC, EvertonSA commented on path_config_rotate.go
> +		Username: "admin",
what if configured user is not called admin?

2022-11-22 19:09 UTC, alexhung requested changes
See comments.

I have not verify this in a local dev environment. I may do that once the PR is in the state ready to be merged.

I also notice this PR is still in 'Draft' state. Is this intentional?

2022-11-22 19:09 UTC, alexhung commented on path_config_rotate.go
> +		Username: "admin",
I agree with @EvertonSA. We should be able to parse the `sub` from the claims and re-use it?

2022-11-22 19:09 UTC, alexhung commented on artifactory_test.go
> +	assert.NoError(t, err)
We should have assertions on the state of the secret values, right? Similar to https://github.com/jfrog/artifactory-secrets-plugin/blob/master/artifactory_test.go#L63

2022-11-23 18:16 UTC, TJM commented
> See comments.
> 
> I have not verify this in a local dev environment. I may do that once the PR is in the state ready to be merged.
> 
> I also notice this PR is still in 'Draft' state. Is this intentional?

I wrote this code like 5 months ago, and was hoping for some feedback ;) That is why it is in draft state :)

2022-11-23 18:22 UTC, TJM commented on artifactory.go
> +	if v1.GreaterThanOrEqual(v2) {
I am guessing that the access API changed in `7.21.1`, so if the Artifactory version is >= 7.21.1 we follow a different process. I would say the lack of "OrEqual" would be a bug, in the event that someone was still using 7.21.1 exactly.

2022-11-23 18:27 UTC, TJM commented on artifactory.go
> +		//    but it is artifactory's job to validate the token, right?
A few lines above, we check the version to ensure we can retrieve the root cert, if we cannot retrieve it, then we cannot validate the token. As mentioned, we are not authenticating a session based on this token, we were just using it to validate the claims. In the event that the token is invalid, Artifactory will simply give an error when we attempt to use it to create the new token. One alternative would be to require the end user to provide the root cert if they are using an older version of artifactory, but I did not write code to handle that, and I don't think it is necessary.

2022-11-23 18:51 UTC, TJM commented on artifactory.go
> +	return b.checkVersion(config, "7.21.1")
This particular version string is only referred to once in code, in this line. The comment above could be made more clear. It seems odd to me that the API would have an incompatible change on a patch release? :) It also occurrs in the README.md where it describes the difference in creating the token.

2022-11-23 18:52 UTC, TJM commented on artifactory.go
> +			// b.Logger().Error("error retrieving root cert", "err", err.Error())
I am trying to figure out why this line is commented out? Perhaps it should be uncommented?

2022-11-23 18:54 UTC, alexhung commented on artifactory.go
> +	return b.checkVersion(config, "7.21.1")
I was looking at both this new and old code (in my editor) so I probably got confused 😄

2022-11-23 18:55 UTC, TJM commented on artifactory_test.go
> +	assert.NoError(t, err)
In this case, we are asserting that the resp is `Nil`, so there is no secret in the response to validate.

2022-11-23 18:58 UTC, TJM commented on path_config_rotate.go
> +		Username: "admin",
Hmm, Maybe it was only certain version of Artifactory that were sensitive to this, but I am pretty sure we had problems when we used anything but "admin" ... I would love to see something like `vault` or whatever here. Lets test this a few different ways hard-coded before changing the code to use the sub. I vaguely recall removing all that stuff and putting it back to "admin" ... but that was 5 months ago :)

2022-11-23 19:02 UTC, TJM commented on path_config_rotate.go
> +		HelpDescription: `
Copied from path_config.go, written by `idcmp` 2 years ago. I doubt it. String literal vs string?

2022-11-23 19:02 UTC, TJM commented on path_config_rotate.go
> +		HelpSynopsis: `Rotate the Artifactory Admin Token.`,
Copied from path_config.go, written by `idcmp` 2 years ago. I doubt it. String literal vs string?

2022-11-23 19:04 UTC, alexhung commented on path_config_rotate.go
> +		HelpSynopsis: `Rotate the Artifactory Admin Token.`,
Yeah, if you don't want to update this in this PR, I'm ok with that.

2022-11-23 19:22 UTC, TJM commented on path_config_rotate.go
> +		HelpSynopsis: `Rotate the Artifactory Admin Token.`,
https://github.com/hashicorp/vault-plugin-secrets-gcp/blob/main/plugin/path_config_rotate_root.go#L120

Based on the code from hashicorp, maybe these are supposed to be constants, but they do have string literal (backticks) and newlines (on both actually). Let's keep those ;)

2022-11-23 21:14 UTC, alexhung commented on path_config_rotate.go
> +		Username: "admin",
For access token, `username` needs to be a valid user account in the system. `admin` is a built user account so it will always work. For other value, it needs to match an existing user account. So if your system doesn't have 'vault' user account then it will fail.

2022-11-23 21:29 UTC, alexhung reviewed
Should this section in README.md be removed? https://github.com/jfrog/artifactory-secrets-plugin/blob/master/README.md?plain=1#L22

2022-11-28 15:19 UTC, TJM commented on artifactory.go
> +	if v1.GreaterThanOrEqual(v2) {
On a related note, according to the [Release Notes](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes#ArtifactoryReleaseNotes-Artifactory7.21.3Cloud%7CSelf-Hosted), 7.21.1 was not released. I still think `OrEqual` is more correct, especially since I made the "version check" more generic (used in other places), but in this actual case, I doubt that it would have affected anyone. :)

2022-11-28 15:24 UTC, TJM commented on path_config_rotate.go
> +		HelpDescription: `
as with the other related comment, this follows the pattern from the example module, and from path_config.go, consistency is good? :)

2022-11-28 18:09 UTC, alexhung commented on path_config_rotate.go
> +		HelpDescription: `
Yeah, it's fine for now. We're planning to spend more time/effort with this project so when the time comes, we will do a bunch of code cleanup.

2022-11-28 21:17 UTC, TJM commented
> Should this section in README.md be removed? https://github.com/jfrog/artifactory-secrets-plugin/blob/master/README.md?plain=1#L22

[Updated README.md](https://github.com/jfrog/artifactory-secrets-plugin/pull/17/commits/44299e51f833c88a58bfb0e3604081ebae4d3010) to remove that section, add a new part to show the /artifactory/config/rotate, and a few minor formatting things that VSCode (Markdown Lint) deemed necessary :)

2022-11-28 21:48 UTC, alexhung commented on path_config_rotate.go
> +		Username: "admin",
No change. So I think we are good for now. In future, we should accommodate any username .

2022-11-28 21:49 UTC, alexhung approved these changes
I feel this looks good now.

@shrajfr12 and @mritunjaykumar  Please review as well.

2022-11-29 01:07 UTC, shrajfr12 approved these changes
LGTM

2022-11-29 20:34 UTC, merged

2022-11-30 14:07 UTC, EvertonSA commented
thanks for merging colleagues, I will test and also provide feedbacks

2022-12-01 09:45 UTC, EvertonSA commented
tested exactly like described and it works fine!