feat: include tokenId in revoke errors
jfrog/artifactory-secrets-plugin pull request #41
Opened 2023-02-24 16:50 UTC by TJM

We have seen some errors revoking tokens, and would like to see the tokenId in the response.

This would tell us whether the tokens are actually being revoked or not, and would also give us a way to take action based on the error (manually revoke by ID)

2023-02-24 17:32 UTC, alexhung commented
@TJM I actually ran into this very same issue couple of weeks ago, troubleshooting another issue. The 204 here is actually HTTP status and the code currently is too specific in error checking. It should check for >= 400 instead.

See https://github.com/jfrog/artifactory-secrets-plugin/blob/master/artifactory.go#L63

(I suspect the API response status code changed from 200 to 204, for the better)

2023-02-24 17:34 UTC, alexhung requested changes
Looks good. Let's update the code to check for just error status codes.

2023-02-24 17:34 UTC, alexhung commented on artifactory.go
>  	if resp.StatusCode != http.StatusOK {
Let's check for `>= http.StatusBadRequest` here.

2023-02-24 20:17 UTC, TJM commented on artifactory.go
>  	if resp.StatusCode != http.StatusOK {
sounds good.

2023-02-24 20:23 UTC, TJM commented on artifactory.go
>  	if resp.StatusCode != http.StatusOK {
I like that this handles any other 2xx code. I question whether we should maybe check for anything over 300, cause that indicates a problem as well. For example redirect would require us to change the code to fix the path or handle the redirect.

2023-02-24 20:24 UTC, TJM commented on artifactory.go
>  	if resp.StatusCode != http.StatusOK {
NOTE: We did confirm that the 204 was indicating that there was no token based on there being no tokens with issue dates that were anywhere close to the start time of the lease. We had 800+ tokens for the "jenkins" user that I made a mass cleanup on, and apparently *some* were still being tracked by Vault :)

2023-02-24 20:27 UTC, alexhung commented on artifactory.go
> +			b.Backend.Logger().Warn("error deleting access tokenID", tokenId, "response", resp, "err", err)
Just notice this. I'm pretty sure the args after the first arg should be in the form of k/v pairs, e.g. key name, value.

See https://github.com/hashicorp/vault/blob/6080a018354f20bbb06b485b25af64be4f3af849/builtin/plugin/backend.go#L167

So for this, this should be:

```go
b.Backend.Logger().Warn("error deleting access tokenID", "tokenId", tokenId, "response", resp, "err", err)
```
Right?

2023-02-24 20:30 UTC, alexhung commented on artifactory.go
>  	if resp.StatusCode != http.StatusOK {
In theory 300s status codes can be problematic. But the API supposes to only return 400s error codes: https://www.jfrog.com/confluence/display/JFROG/JFrog+Platform+REST+API#JFrogPlatformRESTAPI-RevokeTokenbyIDrevoketokenbyid

2023-02-24 20:36 UTC, TJM commented on artifactory.go
> +			b.Backend.Logger().Warn("error deleting access tokenID", tokenId, "response", resp, "err", err)
good catch!

2023-02-24 20:39 UTC, TJM commented on artifactory.go
> +			b.Backend.Logger().Warn("error deleting access tokenID", tokenId, "response", resp, "err", err)
If we had a mock/test setup we could have see that didn't produce the desired log message ;)

2023-02-24 20:52 UTC, alexhung commented on artifactory.go
> +			b.Backend.Logger().Warn("error deleting access tokenID", tokenId, "response", resp, "err", err)
Yes indeed! 😄

2023-02-24 20:53 UTC, alexhung approved these changes

2023-02-25 00:02 UTC, Turhsus approved these changes
LGTM

2023-02-25 00:16 UTC, shrajfr12 approved these changes

2023-02-27 16:48 UTC, merged