feat: use force_revocable tokens in 7.50.3+
jfrog/artifactory-secrets-plugin pull request #45
Opened 2023-03-07 22:02 UTC by TJM

2023-03-07 22:12 UTC, alexhung requested changes
LGTM. I have 2 minor nitpicks.

2023-03-07 22:12 UTC, alexhung commented on artifactory.go
> +		expires_in := strconv.FormatFloat(role.MaxTTL.Seconds(), 'f', -1, 64)
Nitpick: let's use `expiresIn` 😄

2023-03-07 22:12 UTC, alexhung commented on artifactory.go
> +	forceRevoke, err := b.isSupportForceRevokable(config)
Another nitpick: I prefer verb for bool so `supportForceRevocable`?

2023-03-07 22:13 UTC, TJM reviewed
This works, as is, but I think we could design the "version check" stuff better. I'd like to make it so that the version is detected once at config time, then maybe during "reload" ? Then we could switch the "checks" to just compare the version from config.

2023-03-07 22:13 UTC, TJM commented on artifactory.go
> +	forceRevoke, err := b.isSupportForceRevokable(config)
As I was writing this, I was trying to think of a better way to handle "detecting artifactory version" ... I was thinking about querying it once at the start and somehow caching it (maybe in the config or something)?? IT seems kinda silly to keep querying the API multiple times per token creation.

2023-03-07 22:16 UTC, alexhung commented on artifactory.go
> +	forceRevoke, err := b.isSupportForceRevokable(config)
I agree. @danielmkn and I are about to do something similar in the Terraform provider and stores the version in the context.

2023-03-07 22:21 UTC, alexhung commented on artifactory.go
> +	forceRevoke, err := b.isSupportForceRevokable(config)
You probably can add a field to the `Backend` and then call [`InitializeFunc`](https://github.com/hashicorp/vault/blob/main/sdk/framework/backend.go#L60) to fetch the version, then store it in the new field.

2023-03-07 23:05 UTC, TJM commented on artifactory.go
> +	forceRevoke, err := b.isSupportForceRevokable(config)
Should we make that a separate request?

2023-03-08 17:13 UTC, alexhung commented on artifactory.go
> +	forceRevoke, err := b.isSupportForceRevokable(config)
If you're ready to make the changes, let's have it be part of this PR.

2023-03-08 18:07 UTC, TJM commented
Fixed spelling on `revocable` ... how do we get from "revoke" to "revocable" (inflammable means flammable, what a country) ;)

2023-03-08 18:11 UTC, TJM commented on artifactory.go
> +	forceRevoke, err := b.isSupportForceRevokable(config)
I am working on the UserTemplate portion, what we have is working, it is just not very efficient. I create #46 to track this issue.

2023-03-08 18:21 UTC, TJM commented
Sorry, I just noticed my "Makefile" fix for `TOKEN_USERNAME` on the local test artifactory snuck in while I was fixing the spelling. That only affects a local test environment, so I am going to leave it there unless there are objections.

2023-03-08 19:16 UTC, alexhung submitted a review, later dismissed

2023-03-08 19:57 UTC, TJM commented
@alexhung While doing the UserTemplate stuff, I think I might have made an error around the TTL. I assume that the role maxTTL was the number to use, but now I see there is more TTL related logic in the `func (b *backend) pathTokenCreatePerform` function. I am going to have to re-work this. I am not sure which way I will move the logic yet. I am leaning towards passing the expires_in as an argument (optional argument) to the createToken function.

2023-03-08 22:02 UTC, alexhung commented on path_token_create.go
> +	if role.MaxTTL == 0 {
Can we combine these 2 conditions?

e.g.

```go
if role.MaxTTL == 0 || role.MaxTTL > maxLeaseTTL {
    role.MaxTTL = maxLeaseTTL
}
```

2023-03-10 19:20 UTC, TJM commented on path_token_create.go
> +	if role.MaxTTL == 0 {
Yes, also I am working on the "version" query... fixing the tests that had bogus URLs ;)

2023-03-10 21:21 UTC, TJM commented
UPDATE: Rebased (one commit) and pulled out the magic version stuff... as I found it it fails after a reload. I need to sort out initialize, which I will do as part of a separate MR

2023-03-13 16:38 UTC, alexhung approved these changes

2023-03-13 17:13 UTC, shrajfr12 approved these changes
LGTM

2023-03-13 17:16 UTC, merged