fix: post createToken as JSON to fix force_revocable
jfrog/artifactory-secrets-plugin pull request #52
Opened 2023-03-15 18:05 UTC by TJM

ALSO: Make force_revocable/expires_in be "opt-in"

2023-03-15 18:05 UTC, TJM commented
Fixes #50

2023-03-15 18:18 UTC, alexhung requested changes

2023-03-15 18:18 UTC, alexhung commented on artifactory.go
> +	ExpiresIn      int64  `json:"expires_in,"`
Nitpick: extraneous `,` at the end of the tag

2023-03-15 18:18 UTC, alexhung commented on artifactory.go
> -	if u.Scheme == "https" && !strings.Contains(u.Host, "myserver.com:80") && !isProxyExists() {
Not sure about removing this and `isProxyExists()`. 

IIRC these were added for 1) unit testing (not that I agree with the way it was implemented but that's another conversation), 2) to support proxy.

2023-03-15 18:18 UTC, alexhung commented on path_config.go
> +		switch exp := val.(type) {
👍🏼

2023-03-15 18:18 UTC, alexhung commented on README.md
> +### Expiring Tokens
Let's also add a section to document the revocable expiry and persistency thresholds, including a link to: https://www.jfrog.com/confluence/display/JFROG/Access+Tokens#AccessTokens-UsingtheRevocableandPersistencyThresholds

2023-03-15 22:08 UTC, TJM commented on README.md
> +### Expiring Tokens
Like this:

> By default, the Vault generated Artifactory tokens will not show an expiration date, which means that Artifactory will not automatically revoke them.
Vault will revoke the token when its lease expires due to logout or timeout (ttl/max_ttl). The reason for this is because of the
[default Revocable/Persistency Thresholds][artifactory-token-thresholds] in Artifactory. If you would like the artifactory token itself to show an expiration,
and you are using Artifactory v7.50.3 or higher, you can write `use_expiring_tokens=true` to the `/artifactory/config/admin` endpoint.
This will set the `force_revocable=true` parameter and set `expires_in` to either max lease TTL or role max_ttl, whichever is lower.

2023-03-16 15:52 UTC, TJM commented on README.md
> +### Expiring Tokens
Does this documentation update fit the request?

2023-03-16 23:13 UTC, TJM commented on README.md
> +### Expiring Tokens
If this setting is enabled (force_revocable) set, the tokens are made to be persistent, which will make them show up in the UI. regardless of their TTL.

I am thinking that if the force_revocable flag is set, access is required to check the database. There is no other way that I can think of to make the tokens revocable.


Tommy

2023-03-17 17:58 UTC, alexhung commented on README.md
> +### Expiring Tokens
That's fair.

2023-03-17 17:59 UTC, alexhung approved these changes

2023-03-17 18:00 UTC, alexhung requested changes

2023-03-17 18:00 UTC, alexhung commented on artifactory.go
> -	if u.Scheme == "https" && !strings.Contains(u.Host, "myserver.com:80") && !isProxyExists() {
Sorry, I am not seeing this and the other similar code being reverted.

2023-03-20 15:56 UTC, TJM commented on artifactory.go
> -	if u.Scheme == "https" && !strings.Contains(u.Host, "myserver.com:80") && !isProxyExists() {
I could not see any reason to create a TLS connection to the target server before trying to connect via http.Client. This TLS connection is not being used. It just basically connects, then ignores the connection. I have to think that this is a remnant of some old code, that maybe implemented the http connection differently. These exception cases were indeed added to support unit testing (skip TLS connection attempt to bogus unit test server) and proxy (with a proxy, you don't directly connect to the target server). As the tls connection is not being used, the code seems completely unnecessary. I can put it back, but since I was duplicating that POST function, I was tracing through it and could not justify it being there.

2023-03-20 16:14 UTC, TJM commented
I just rebased, to ensure there would be no unexpected issue when merging.

2023-03-20 17:57 UTC, alexhung commented on artifactory.go
> -	if u.Scheme == "https" && !strings.Contains(u.Host, "myserver.com:80") && !isProxyExists() {
I agree with your assessment. I don't know the history of this particular block of code. My conservative side wants to keep it to minimize change, but on the other hand removing this is the 'right' thing to do.

Let keep this removal and we can manage any downstream effect.

2023-03-20 17:57 UTC, alexhung approved these changes

2023-03-20 18:58 UTC, danielmkn approved these changes

2023-03-20 20:56 UTC, shrajfr12 approved these changes
lgtm

2023-03-20 20:57 UTC, merged