feat: improve path_config_rotate test coverage
jfrog/artifactory-secrets-plugin pull request #88
Opened 2023-04-26 04:02 UTC by TJM

Add a few error state tests to improve test coverage on config/rotate

2023-04-26 04:07 UTC, TJM commented
We have all the "positive" test cases covered, but I am not sure how to create some of the errors. If you have ideas, let me know. I am going to tackle /config/admin next.

2023-04-26 05:19 UTC, TJM commented
* `path_config.go`
  * master: 68.1% (62.4% overall)
  * this branch: 91.2% (68.2% overall)

2023-04-26 16:49 UTC, TJM commented on path_config.go
> -		b.Logger().Warn("config update use_expiring_tokens", "use_expiring_tokens", val)
I noticed this while testing the expiring_tokens, this was in here for debug, removed.

2023-04-26 17:50 UTC, alexhung commented
> Learned something... ![Screenshot 2023-04-26 at 8 46 13 AM](https://user-images.githubusercontent.com/1641316/234613903-dbc6318d-d31e-4bd2-ba69-8c5f63a65f59.png)
> 
> We don't need this case statement to check for `bool`, because no matter what we submit, it comes out as a string? although this feels like a bug to me :)

Most likely because the attribute is defined as `TypeString` (https://github.com/jfrog/artifactory-secrets-plugin/blob/master/path_config.go#L33) 😄 

Instead we should use `TypeBool`.

2023-04-26 17:56 UTC, alexhung requested changes
LGTM. Just the commented out line of code.

2023-04-26 17:56 UTC, alexhung commented on path_config_rotate_test.go
> +	// assert.Contains(t, resp.Data["error"], "error parsing existing AccessToken")
Is this still needed?

2023-05-04 01:27 UTC, TJM commented on path_config_rotate_test.go
> +	// assert.Contains(t, resp.Data["error"], "error parsing existing AccessToken")
This is a matter of opinion, I think that it should contain the error, but it does not. I want to adjust this in a future MR.. trying to not change a bunch of code while writing the tests ;)

2023-05-04 01:27 UTC, TJM commented
> > Learned something... ![Screenshot 2023-04-26 at 8 46 13 AM](https://user-images.githubusercontent.com/1641316/234613903-dbc6318d-d31e-4bd2-ba69-8c5f63a65f59.png)
> > We don't need this case statement to check for `bool`, because no matter what we submit, it comes out as a string? although this feels like a bug to me :)
> 
> Most likely because the attribute is defined as `TypeString` (https://github.com/jfrog/artifactory-secrets-plugin/blob/master/path_config.go#L33) 😄
> 
> Instead we should use `TypeBool`.

Created a new issue for this.

2023-05-04 15:49 UTC, alexhung approved these changes

2023-05-04 15:50 UTC, merged

2023-05-04 16:54 UTC, TJM commented on path_config_rotate_test.go
> +	// assert.Contains(t, resp.Data["error"], "error parsing existing AccessToken")
See #92